# Generated by Django 5.2.1 on 2025-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alien_number', models.CharField(blank=True, help_text='A-Number (if available)', max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
