# Generated by Django 5.2.1 on 2025-06-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_alien_number_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='principal_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='clients.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='relationship_type',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal Applicant'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child')], default='PRINCIPAL', max_length=20),
        ),
    ]
