# Generated by Django 5.2.1 on 2025-06-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_principal_applicant_client_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='relationship_type',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal Applicant'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling')], default='PRINCIPAL', max_length=20),
        ),
    ]
